// Study cases generated by Neo-trade/research/export_cases.py into public/cases.
// Prices are integers in points (1e-5); times are UTC seconds (the broker server runs on GMT+0).

import { useEffect, useState } from 'react';

export type Tf = 'D1' | 'H4' | 'M15';
export const CHART_ORDER: Tf[] = ['D1', 'H4', 'M15'];

export interface Candles {
  t: number[];
  o: number[];
  h: number[];
  l: number[];
  c: number[];
  /** Colour family 0-3 (green, blue, red, pink), plus 4 when the candle is a Build candle. */
  k: number[];
}

export interface LpZone {
  tf: 'M15' | 'H4' | 'D1' | 'W1';
  hi: number;
  lo: number;
  /** 1 = GLP, -1 = RLP, 0 = unbroken. */
  d: number;
  m: number;
  x: number;
}

export interface Overlays {
  lp: LpZone[];
  /** Protected level of the chart timeframe as [from, to, price, state] runs. */
  prot: number[][];
  /** Range boxes as [from, to, low, high]. */
  ranges: number[][];
  /** Protected levels of the higher timeframes. */
  levels: { tf: string; p: number; s: number }[];
  swings: { tf: string; p: number; k: number; x: number }[];
  /** Sweep marks as [index, direction]. */
  marks: number[][];
}

export interface ChartData extends Candles, Overlays {
  forming: boolean;
}

export interface CheckItem {
  id: number;
  group: 'context' | 'zone' | 'reaction' | 'location';
  label: string;
  met: boolean;
  oppose: boolean;
  detail: string;
}

export interface Paragraph {
  title: string;
  text: string;
}

export interface CaseDoc {
  id: string;
  symbol: string;
  time: number;
  dir: 1 | -1;
  price: number;
  tip: number;
  score: number;
  total: number;
  charts: Record<Tf, ChartData>;
  checklist: CheckItem[];
  analysis: Paragraph[];
}

export interface CaseAfter {
  result: 'run' | 'fail';
  travel: number;
  charts: Record<Tf, Candles>;
  markers: { best: { t: number; p: number } | null; out: { t: number } | null };
  outcome: Paragraph[];
}

export interface ScoreBand {
  label: string;
  n: number;
  run: number;
  fail: number;
}

export interface CaseIndex {
  symbol: string;
  total: number;
  runPips: number;
  failPips: number;
  stats: { tips: number; run: number; fail: number; bands: ScoreBand[] };
  cases: { id: string; t: number; score: number }[];
}

type Packed = Candles & { base: number };

/** Files store times as the first stamp plus steps in minutes, and prices as offsets from `base`. */
function unpack<T extends Packed>(chart: T): T {
  const t: number[] = [];
  chart.t.forEach((value, i) => t.push(i === 0 ? value : t[i - 1] + value * 60));
  const lift = (values: number[]) => values.map((value) => value + chart.base);
  return { ...chart, t, o: lift(chart.o), h: lift(chart.h), l: lift(chart.l), c: lift(chart.c) };
}

async function getJson<T>(name: string): Promise<T> {
  const response = await fetch(`${import.meta.env.BASE_URL}cases/${name}`);
  if (!response.ok) throw new Error(`Cannot load ${name}: ${response.status}`);
  return (await response.json()) as T;
}

let indexPromise: Promise<CaseIndex> | undefined;

export function loadIndex(): Promise<CaseIndex> {
  indexPromise ??= getJson<CaseIndex>('index.json');
  return indexPromise;
}

export async function loadCase(id: string): Promise<CaseDoc> {
  const doc = await getJson<CaseDoc>(`${id}.json`);
  for (const tf of CHART_ORDER) doc.charts[tf] = unpack(doc.charts[tf] as ChartData & Packed);
  return doc;
}

export async function loadAfter(id: string): Promise<CaseAfter> {
  const after = await getJson<CaseAfter>(`${id}.after.json`);
  for (const tf of CHART_ORDER) after.charts[tf] = unpack(after.charts[tf] as Packed);
  return after;
}

export function useCaseIndex(): { index: CaseIndex | null; error: string | null } {
  const [index, setIndex] = useState<CaseIndex | null>(null);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => {
    let alive = true;
    loadIndex().then(
      (value) => alive && setIndex(value),
      (reason) => alive && setError(String(reason)),
    );
    return () => {
      alive = false;
    };
  }, []);
  return { index, error };
}

export function joinCandles(a: Candles, b: Candles, count: number): Candles {
  const keys = ['t', 'o', 'h', 'l', 'c', 'k'] as const;
  const out = {} as Candles;
  for (const key of keys) out[key] = a[key].concat(b[key].slice(0, count));
  return out;
}

export function sliceCandles(a: Candles, end: number): Candles {
  return { t: a.t.slice(0, end), o: a.o.slice(0, end), h: a.h.slice(0, end), l: a.l.slice(0, end), c: a.c.slice(0, end), k: a.k.slice(0, end) };
}

export function formatTime(seconds: number): string {
  const iso = new Date(seconds * 1000).toISOString();
  return `${iso.slice(8, 10)}/${iso.slice(5, 7)}/${iso.slice(0, 4)} ${iso.slice(11, 16)}`;
}

export function formatPrice(points: number): string {
  return (points / 100000).toFixed(5);
}

// ---- Personal progress, kept in this browser only ---------------------------------------------------------

export type Prediction = 'buy' | 'sell' | 'skip';

export interface Progress {
  pred?: Prediction;
  /** 1 low, 2 medium, 3 high. */
  conf?: number;
  note?: string;
  revealed?: boolean;
  result?: 'run' | 'fail';
  dir?: 1 | -1;
  travel?: number;
}

const STORE_KEY = 'zos.cases.v1';

export function readAllProgress(): Record<string, Progress> {
  try {
    return JSON.parse(localStorage.getItem(STORE_KEY) || '{}') as Record<string, Progress>;
  } catch {
    return {};
  }
}

export function writeProgress(id: string, progress: Progress | null): void {
  try {
    const all = readAllProgress();
    if (progress) all[id] = progress;
    else delete all[id];
    localStorage.setItem(STORE_KEY, JSON.stringify(all));
  } catch {
    // Storage can be unavailable (private window); the page still works without saving.
  }
}

/** A run is right when the direction was called; a failed tip is right when it was skipped or faded. */
export function isCorrect(progress: Progress): boolean | null {
  if (!progress.revealed || !progress.pred || !progress.result || !progress.dir) return null;
  const called = progress.pred === (progress.dir === 1 ? 'buy' : 'sell');
  return progress.result === 'run' ? called : !called;
}
